sudo: false
language: cpp
os:
    - linux
    - osx
compiler:
  - gcc
before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc --without-multilib  ; fi
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  global:
    - OMP_NUM_THREADS=4
    - LANG="en_US.UTF-8"

before_script:
    - mkdir build
    - cd build
script:
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - ./openmp_sample